# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += testing/DiskMastetLibTest/DiskMastetLibTest.pro \
    testing/DiskMasterTestQt/DiskMasterTestQt.pro \
    DiskMasterTool/DiskMaster.pro \
    src/Imager/Imager.pro \
    FileChecker/FileChecker.pro \
    RaidAnalyzer/RaidAnalyzer.pro \
    SignaturesEditor/SignaturesEditor.pro \
    src/DiskMasterLib/DiskMasterLib.pro \
    src/libui/libui.pro \
    src/WidgetLibrary/WidgetLibrary.pro \
    JsonReader/JsonReader.pro \
    QtConsoleApplication1/QtConsoleApplication1.pro
