#ifndef WIDGETLIBRARY_GLOBAL_H
#define WIDGETLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WIDGETLIBRARY_LIB
# define WIDGETLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define WIDGETLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETLIBRARY_GLOBAL_H
